"""The generic data shape every source produces and every sender consumes.

This is the contract that decouples "where listings come from" from "where
they get sent". A new source only needs to map its own API response onto
this model; senders never know or care which source produced an Item.
"""
from typing import Literal, Optional

from pydantic import BaseModel


class Media(BaseModel):
    type: Literal["photo", "video"]
    url: str


class Item(BaseModel):
    id: str  # stable unique id (Divar calls this "token") used for dedup/state
    title: str = ""
    price: int = 0  # 0 / falsy is rendered as "توافقی" / "negotiable" by senders
    description: str = ""
    location: str = ""  # human-readable location line
    media: list[Media] = []
    features: list[tuple[str, str]] = []  # e.g. [("متراژ", "۱۰۰"), ...]
    tags: list[str] = []  # hashtags, pre-generated by the source
    url: str = ""  # optional link back to the original listing
    source: str = ""  # which source produced this, e.g. "divar"

    # If set, senders use this text exactly as written instead of building a
    # message from title/price/features/etc. Use this when the source is
    # itself a finished piece of writing (e.g. relaying an existing Telegram
    # post) rather than structured listing data to be templated.
    raw_text: Optional[str] = None
