"""The generic data shape every source produces and every sender consumes.

This is the contract that decouples "where listings come from" from "where
they get sent". A new source only needs to map its own API response onto
this model; senders never know or care which source produced an Item.
"""
from pydantic import BaseModel


class Item(BaseModel):
    id: str  # stable unique id (Divar calls this "token") used for dedup/state
    title: str
    price: int = 0  # 0 / falsy is rendered as "توافقی" / "negotiable" by senders
    description: str = ""
    location: str = ""  # human-readable location line
    images: list[str] = []
    features: list[tuple[str, str]] = []  # e.g. [("متراژ", "۱۰۰"), ...]
    tags: list[str] = []  # hashtags, pre-generated by the source
    url: str = ""  # optional link back to the original listing
    source: str = ""  # which source produced this, e.g. "divar"
