"""The generic data shape every source produces and every sender consumes.

This is the contract that decouples "where listings come from" from "where
they get sent". A new source only needs to map its own API response onto
this model; senders never know or care which source produced an Item.
"""
from typing import Literal, Optional

from pydantic import BaseModel


class Media(BaseModel):
    type: Literal["photo", "video"]
    url: str


class ChannelLink(BaseModel):
    """One 'follow us elsewhere' link for a message footer. label is the
    clickable text (the same brand label across platforms is normal - only
    the url differs); senders render it as an HTML anchor, Markdown link,
    or plain 'label: url' depending on what that platform actually supports."""
    label: str
    url: str


class Item(BaseModel):
    id: str  # stable unique id (Divar calls this "token") used for dedup/state
    title: str = ""
    price: int = 0  # 0 / falsy is rendered as "توافقی" / "negotiable" by senders
    description: str = ""
    location: str = ""  # human-readable location line
    media: list[Media] = []
    features: list[tuple[str, str]] = []  # e.g. [("متراژ", "۱۰۰"), ...]
    tags: list[str] = []  # hashtags, pre-generated by the source
    url: str = ""  # optional link back to the original listing
    source: str = ""  # which source produced this, e.g. "divar"

    # If set, senders use this text exactly as written instead of building a
    # message from title/price/features/etc. Use this when the source is
    # itself a finished piece of writing (e.g. relaying an existing Telegram
    # post) rather than structured listing data to be templated.
    raw_text: Optional[str] = None

    # Optional "follow us elsewhere" footer links, rendered by each sender
    # in whatever markup that platform supports (or a plain fallback).
    channel_links: list[ChannelLink] = []

    # Optional per-item destination overrides, keyed by sender name (e.g.
    # {"telegram": "@customer_channel"}). A sender uses this chat id instead
    # of its own static config default when present. If non-empty, delivery
    # is restricted to exactly these sender names - this is how "website"
    # sends a customer's post only to the platforms they filled in, instead
    # of falling back to your own default channels for the ones they didn't.
    destination_overrides: dict[str, str] = {}
