name: Run bots

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_RELAY_BOT_TOKEN: ${{ secrets.TELEGRAM_RELAY_BOT_TOKEN }}
          TELEGRAM_RELAY_CHAT_IDS: ${{ secrets.TELEGRAM_RELAY_CHAT_IDS }}
          RUBIKA_BOT_TOKEN: ${{ secrets.RUBIKA_BOT_TOKEN }}
          EITAA_BOT_TOKEN: ${{ secrets.EITAA_BOT_TOKEN }}
          BALE_BOT_TOKEN: ${{ secrets.BALE_BOT_TOKEN }}
